version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ledger_db
    environment:
      POSTGRES_USER: tergel
      POSTGRES_PASSWORD: tergelgod
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: ledger_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://tergel:tergelgod@postgres:5432/mydatabase?sslmode=disable"

volumes:
  pgdata: