version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tergel
      POSTGRES_PASSWORD: tergelgod
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
    
      DATABASE_URL: postgres://tergel:tergelgod@db:5432/mydatabase?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db